import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class despegarSet():
#------------------#
    def __init__(self, driver):
        self.driver = driver

        # Accomodations Arguments---#
        self.accomm = (By. CSS_SELECTOR, 'body > nav > div.header-navigation.-first > div > div.header-products-container > ul > li:nth-child(1) > a > div')
        self.city = (By. CSS_SELECTOR, '#searchbox-sbox-box-hotels > div > div > div > div > div.sbox5-box-content > div.sbox5-box-places-ovr.sbox-places-container--3kBK7 > div > div > div > input')        
        self.dates = (By. CSS_SELECTOR, '#searchbox-sbox-box-hotels > div > div > div > div > div.sbox5-box-content > div.sbox5-box-dates-checkbox-container > div > div.sbox5-dates-input1-container > div > div > div > div > input')
        self.accomodation_enterdate = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > div:nth-child(3) > div.sbox5-monthgrid-dates.sbox5-monthgrid-dates-31 > div.sbox5-monthgrid-datenumber.sbox5-monthgrid-datenumber-31')                                       
        self.exitdate = (By. CSS_SELECTOR, '#searchbox-sbox-box-hotels > div > div > div > div > div.sbox5-box-content > div.sbox5-box-dates-checkbox-container > div > div.sbox5-dates-input2-container > div > div > div > div')
        self.accomodation_exdate = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > div:nth-child(4) > div.sbox5-monthgrid-dates.sbox5-monthgrid-dates-30 > div.sbox5-monthgrid-datenumber.sbox5-monthgrid-datenumber-30.-weekday')                                                    
        self.apply = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.calendar-footer > div.calendar-footer-cta-container > button')
        self.search_button = (By. CSS_SELECTOR, '#searchbox-sbox-box-hotels > div > div > div > div > div.sbox5-box-content > button')
        self.close = (By. XPATH, '/html/body/nav/div[4]/div[1]/i')
        self.unnders = (By. XPATH, '//*[@id="lgpd-banner"]/div/a[2]/em')
        self.destiny = (By. CSS_SELECTOR, 'body > div.ac-wrapper.-show.sbox-ab-ls > div.ac-container > div:nth-child(1) > ul > li:nth-child(1) > span')
        self.order_by = (By. CSS_SELECTOR, 'body > aloha-app-root > aloha-results > div > div > div > div.results-column > div.results-items-wrapper > aloha-list-view-container > div.secondary-toolbar-wrapper.-eva-3-mb-xlg > aloha-order-inline > div > aloha-select > div > div > select')
        self.view_detail = (By. CSS_SELECTOR, 'body > aloha-app-root > aloha-results > div > div > div > div.results-column > div.results-items-wrapper > aloha-list-view-container > div:nth-child(4) > div:nth-child(1) > aloha-vacation-rentals-cluster > div > div > div.cluster-pricebox-container > aloha-cluster-pricebox-container > div > div.pricebox-top-container > div.pricebox-action > aloha-button > button')
        self.view_rooms = (By. CSS_SELECTOR, 'body > aloha-app-root > aloha-detail > div:nth-child(1) > div.detail-container > div > div > aloha-infobox-container > aloha-infobox-wrapper-container > div > div.eva-3-pricebox-cluster.-responsive > div > aloha-infobox-shopping-content > div > div.pricebox-action.-eva-3-mt-lg.pricebox-button > aloha-button > button')
        self.room_reserve = (By. CSS_SELECTOR, '#roompacks-container-wrapper > aloha-roompacks-container > aloha-roompacks-grid-container > div.body > div.col-6.-eva-3-bc-white > aloha-reservation-summary-container > div > aloha-next-step-button > div > aloha-button > button')
        self.room_next = (By. CSS_SELECTOR, 'body > app-root > app-pricebox-sticky > pricebox-sticky > div > div.pricebox-content-container > div.buttons-container > button')
        self.arrow_right = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > a.calendar-arrow-right')
        self.reserve = (By. CSS_SELECTOR, '#roompacks-container-wrapper > aloha-roompacks-container > aloha-roompacks-grid-container > div.body > div.col-6.-eva-3-bc-white > aloha-reservation-summary-container > div > aloha-next-step-button > div > aloha-button > button')

        # Flights Arguments---#
        self.flights_button = (By. CSS_SELECTOR, 'body > nav > div.header-navigation.-first > div > div.header-products-container > ul > li:nth-child(2) > a')
        self.flight_destiny = (By. CSS_SELECTOR, '#searchbox-sbox-box-flights > div > div > div > div.sbox5-box-content--2pcCl.sbox5-flightType-roundTrip--fSJm8 > div.sbox5-segments--lzKBc > div:nth-child(1) > div.sbox5-places-component--1i-wZ > div > div.sbox-places-destination--1xd0k.sbox-places-origin-destination--1I6U9.show-dotted-line--1lOfj.sbox-places-dest-override > div > div > input')
        self.flight_date = (By. CSS_SELECTOR, '#searchbox-sbox-box-flights > div > div > div > div.sbox5-box-content--2pcCl.sbox5-flightType-roundTrip--fSJm8 > div.sbox5-segments--lzKBc > div:nth-child(1) > div.sbox5-dates-component--3dTHh > div > div.sbox5-dates-input1-container > div > div > div > div > input')
        self.enter_flight_date = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > div:nth-child(3) > div.sbox5-monthgrid-dates.sbox5-monthgrid-dates-28 > div.sbox5-monthgrid-datenumber.sbox5-monthgrid-datenumber-28')
        self.exitflight_date = (By. CSS_SELECTOR, '#searchbox-sbox-box-flights > div > div > div > div.sbox5-box-content--2pcCl.sbox5-flightType-roundTrip--fSJm8 > div.sbox5-segments--lzKBc > div:nth-child(1) > div.sbox5-dates-component--3dTHh > div > div.sbox5-dates-input2-container > div > div > div > div > input')
        self.enter_exitflight_date = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > div:nth-child(4) > div.sbox5-monthgrid-dates.sbox5-monthgrid-dates-31 > div.sbox5-monthgrid-datenumber.sbox5-monthgrid-datenumber-28')                                               
        self.passengers_class = (By. CSS_SELECTOR, '#searchbox-sbox-box-flights > div > div > div > div.sbox5-box-content--2pcCl.sbox5-flightType-roundTrip--fSJm8 > div.sbox5-segments--lzKBc > div:nth-child(1) > div.sbox5-distribution-passengers--dbiHH > div > div > div > div')
        self.adult_plus = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div > div > div.stepper__distribution_container > div:nth-child(1) > div.stepper__room__row__stepper__contaer > div > button.steppers-icon-right.stepper__icon')
        self.menor_plus = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div > div > div.stepper__distribution_container > div:nth-child(2) > div.stepper__room__row__stepper__contaer > div > button.steppers-icon-right.stepper__icon')
        self.age_menor1 = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div > div > div.stepper__distribution_container > div:nth-child(3) > div.select__row__options__container > div > div > select')
        self.age_menor2 = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div > div > div.stepper__distribution_container > div:nth-child(4) > div.select__row__options__container > div > div > select')
        self.age_menor3 = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div > div > div.stepper__distribution_container > div:nth-child(5) > div.select__row__options__container > div > div > select')
        self.clase = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div > div > div.sbox5-cabin-class--1ReWi > div.sbox5-cabin-class-select--3cEQw > div > div > div > select')
        self.flight_apply = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div > div > div.stepper__room__footer > a')
        self.flight_search = (By. CSS_SELECTOR, '#searchbox-sbox-box-flights > div > div > div > div.sbox5-box-content--2pcCl.sbox5-flightType-roundTrip--fSJm8 > div.sbox5-button-container--1X4O8 > button')
        
        # Packages Arguments---#
        self.packages_button = (By. CSS_SELECTOR, 'body > nav > div.header-navigation.-first > div > div.header-products-container > ul > li:nth-child(3) > a > div')
        self.package_destiny = (By. CSS_SELECTOR, '#searchbox-sbox-box-packages > div > div > div > div > div.sbox5-box-content--7v1p9 > div.sbox5-places-component--25H8Q > div > div.sbox-places-destination--zh4wy.sbox-places-origin-destination--3rJNZ.sbox-places-destination-override > div > div > input')
        self.package_rooms = (By. CSS_SELECTOR, '#searchbox-sbox-box-packages > div > div > div > div > div.sbox5-box-content--7v1p9 > div.sbox5-distribution-component--2kPjz > div > div > div')
        self.package_substract = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div > div > div.stepper__room > div.stepper__distribution_container > div:nth-child(1) > div.stepper__room__row__stepper__contaer > div > button.steppers-icon-left.stepper__icon')
        self.packagerooms_apply = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div > div > div.stepper__room__footer > a.sbox5-3-btn.-md.-primary')
        self.package_notdate = (By. CSS_SELECTOR, '#searchbox-sbox-box-packages > div > div > div > div > div.sbox5-box-content--7v1p9 > div.sbox5-dates-component--3wQuZ > div.sbox5-without-dates-container--suFCT > span > span > label > span.switch-container')
        self.package_search = (By. CSS_SELECTOR, '#searchbox-sbox-box-packages > div > div > div > div > div.sbox5-box-content--7v1p9 > div.sbox5-button-container--3uIuw > button')
        self.package_travel = (By. CSS_SELECTOR, 'body > app-root > div > div:nth-child(8) > meta-component > div > offers > div > div.offer-cards-container.offers-first-row.grid-row > offer-card:nth-child(1) > div > a > div > div.offer-card-info > div > offer-card-detail-info > div.offer-card-title.small-title')
        self.package_travel_aux = (By. CSS_SELECTOR, '#Offers_4273 > meta-component > div > offers > div > div.offer-cards-container.offers-first-row > offer-card:nth-child(1) > div > a > div > div.offer-card-info > div > offer-card-detail-info > div.offer-card-title.small-title')

        #Offers Arguments---#
        self.offers_button = (By. CSS_SELECTOR, 'body > nav > div.header-navigation.-first > div > div.header-products-container > ul > li:nth-child(4) > a > div')
        self.offer_package = (By. CSS_SELECTOR, '#KillersRow1 > meta-component > div > offers > div > div > div.side-text.title-wrapper > eva-button')
        self.view_travel = (By. CSS_SELECTOR, '#AR1 > meta-component > div > offers > div > div.offer-cards-container.offers-first-row > offer-card:nth-child(1) > div > a > div > div.offer-card-info > div > offer-card-detail-info > div.offer-card-title.small-title')
        self.see_travel = (By. CSS_SELECTOR, 'body > aloha-app-root > aloha-results > div > div > div.results-wrapper.-eva-3-mt-xlg > div.results-column > div.results-items-wrapper > aloha-list-view-container > div.-eva-3-mb-xlg > aloha-wizard-wrapper > wizard > div > div > div.wizard-stepper-container.wizard-step-container > wizard-step:nth-child(5) > div > div > div > a')
        self.close_see_travel = (By. CSS_SELECTOR, '#wizard > div > div.sheet-header > i.modal-close.eva-3-icon-close')
        self.travel_next = (By. CSS_SELECTOR, 'body > aloha-app-root > aloha-results > div > div > div.results-wrapper.-eva-3-mt-xlg > div.results-column > div.results-items-wrapper > aloha-list-view-container > div.-eva-3-mb-xlg > aloha-cluster-container > div > div > div.cluster-pricebox-container > aloha-cluster-pricebox-container > div > div.pricebox-top-container > div.pricebox-action > aloha-button > button')
        self.see_rooms = (By. CSS_SELECTOR, 'body > aloha-app-root > aloha-detail > div:nth-child(1) > div.detail-container > div > div > aloha-infobox-container > aloha-infobox-wrapper-container > div > div.eva-3-pricebox-cluster.-responsive > div.price-wrapper > aloha-infobox-shopping-content > div > div.pricebox-action.-eva-3-mt-lg.pricebox-button > aloha-button > button')
        self.continue_travel = (By. CSS_SELECTOR, '#roompacks-container-wrapper > aloha-roompacks-container > aloha-roompacks-grid-container > div.body > div.col-6.-eva-3-bc-white > aloha-reservation-summary-container > div > aloha-next-step-button > div > aloha-button > button')
        self.buy_button = (By. CSS_SELECTOR, '#trips-cluster-selected-position > trips-cluster-selected > span > cluster > div > div.cluster-container.SELECTED.border-top-complete > div.cluster-pricebox-container.CLUSTER > fare > span > span > div > buy-button > a > div')                
        self.continue_2 = (By. CSS_SELECTOR, '#upselling-popup-position > upselling-popup > div > div.modal-footer.-eva-3-bc-gray-4.-loyalty > div > div > button')
        self.endoffer = (By. CSS_SELECTOR, 'body > app-root > app-pricebox-sticky > pricebox-sticky > div > div.pricebox-content-container > div.buttons-container > button')

        #Rent Arguments---#
        self.rents_button = (By. CSS_SELECTOR, 'body > nav > div.header-navigation.-first > div > div.header-products-container > ul > li:nth-child(5) > a > div')
        self.rents_destiny = (By. CSS_SELECTOR, '#searchbox-sbox-box-vacationrentals > div > div > div > div > div.sbox5-box-content > div.sbox5-box-places-ovr.sbox-places-container--3kBK7 > div > div > div > input')
        self.rents_cordoba = (By. CSS_SELECTOR, 'body > div.ac-wrapper.-desktop.-show.sbox-ab-ls > div > div:nth-child(1) > ul > li.item.-active')
        self.rents_enterdate = (By. CSS_SELECTOR, '#searchbox-sbox-box-vacationrentals > div > div > div > div > div.sbox5-box-content > div.sbox5-box-dates-checkbox-container > div > div.sbox5-dates-input1-container > div > div > div > div > input')
        self.rents_date = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > div:nth-child(3) > div.sbox5-monthgrid-dates.sbox5-monthgrid-dates-28 > div.sbox5-monthgrid-datenumber.sbox5-monthgrid-datenumber-28')
        self.rents_exitdate = (By. CSS_SELECTOR, '#searchbox-sbox-box-vacationrentals > div > div > div > div > div.sbox5-box-content > div.sbox5-box-dates-checkbox-container > div > div.sbox5-dates-input2-container > div > div > div > div > input')
        self.rents_date2 = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > div:nth-child(4) > div.sbox5-monthgrid-dates.sbox5-monthgrid-dates-31 > div.sbox5-monthgrid-datenumber.sbox5-monthgrid-datenumber-28 > div')
        self.rents_applydate = (By. CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.calendar-footer > div.calendar-footer-cta-container > button')
        self.rents_search = (By. CSS_SELECTOR, '#searchbox-sbox-box-vacationrentals > div > div > div > div > div.sbox5-box-content > button')
    
        #Activities Arguments---#
        self.activ_button = (By. CSS_SELECTOR, 'body > nav > div.header-navigation.-first > div > div.header-products-container > ul > li:nth-child(6) > a > div')
        self.activ_enterdestiny = (By. CSS_SELECTOR, '#searchbox-sbox-box-tickets > div > div > div > div > div.sbox5-box-row--28ps6 > div.sbox5-box-places-container--WQVO0 > div > div > div > div > input')
        self.activ_destiny = (By. CSS_SELECTOR, 'body > div.ac-wrapper.-desktop.-show.sbox-ab-ls > div > div:nth-child(1) > ul > li.item.-active')
        self.activ_search = (By. CSS_SELECTOR, '#searchbox-sbox-box-tickets > div > div > div > div > div.sbox5-box-row--28ps6 > div.sbox5-box-search-button-container--3zL-J > button')
        self.activ_select = (By. CSS_SELECTOR, '#slider_id_1 > swiper > div > div.swiper-slide.swiper-slide-active > media-picture > div > div')
        self.activ_seeoption = (By. CSS_SELECTOR, '#bodyID > div:nth-child(2) > div > div:nth-child(2) > div > div > div > div.detail-cluster-container > div.detail-product-pricebox.contenedor-pricebox.tour-pricebox-content > tour-price-box > div > div.tour-price-box-container > div.action-button > a')
        self.activ_sel_date = (By. CSS_SELECTOR, '#bodyID > div:nth-child(2) > div > div:nth-child(2) > div > div > div > div.detail-modules > tour-modalities > div > ul > li:nth-child(1) > tour-modality-cluster > div > div > em > div > div.cluster-container > div.cluster-pricebox-container > div > div > div.action-buttons.-date > span.button-date > a > em')
        self.activ_ddate = (By. CSS_SELECTOR, '#bodyID > div:nth-child(2) > div > div:nth-child(2) > div > div > div > div.detail-modules > tour-modalities > div > ul > li:nth-child(1) > tour-modality-cluster > div > div > em > div > div.cluster-container > div.cluster-content > div.modality-selection > section:nth-child(1) > date-picker > div > span > span > span > div > div.calendar-body > div:nth-child(6) > span:nth-child(7)')
        self.activ_sel_time = (By. CSS_SELECTOR, '#bodyID > div:nth-child(2) > div > div:nth-child(2) > div > div > div > div.detail-modules > tour-modalities > div > ul > li:nth-child(1) > tour-modality-cluster > div > div > em > div > div.cluster-container > div.cluster-content > div.modality-selection > section:nth-child(2) > div > div > select')
        self.activ_time = (By. CSS_SELECTOR, '#bodyID > div:nth-child(4) > div > div:nth-child(2) > div > div > div > div.detail-modules > tour-modalities > div > ul > li:nth-child(1) > tour-modality-cluster > div > div > em > div > div.cluster-container > div.cluster-content > div.modality-selection > section:nth-child(2) > div > div > select')
        self.activ_add = (By. CSS_SELECTOR, '#bodyID > div:nth-child(2) > div > div:nth-child(2) > div > div > div > div.detail-modules > tour-modalities > div > ul > li:nth-child(1) > tour-modality-cluster > div > div > em > div > div.cluster-container > div.cluster-pricebox-container > div > div > div.action-buttons > span.button-add')
        self.activ_cart = (By. CSS_SELECTOR, 'body > app-root > app-results > div > div.date-filter.top-elements-container > div > app-cart > div > div')
        self.activ_arrowright = (By. CSS_SELECTOR, '#bodyID > div:nth-child(2) > div > div:nth-child(2) > div > div > div > div.detail-modules > tour-modalities > div > ul > li:nth-child(1) > tour-modality-cluster > div > div > em > div > div.cluster-container > div.cluster-content > div.modality-selection > section:nth-child(1) > date-picker > div > span > span > span > div > div.calendar-header > span.eva-3-icon-arrow-right')

        #Getaways Arguments---#
        self.getaways_button = (By. CSS_SELECTOR, 'body > nav > div.header-navigation.-first > div > div.header-products-container > ul > li:nth-child(7) > a > div')
        self.getaways_culture = (By. CSS_SELECTOR, '#categories > div.carousel-cards-container > div.cards-container-list.swiper-tags.cards-container-listinitialized.cards-container-listhorizontal > ul > li.card-item.wrapper-tag.-eva-3-tc.tagsCulture.ng-star-inserted > a > div > div.img.-eva-3-center.ng-star-inserted')
        self.getaways_destiny = (By. CSS_SELECTOR, 'body > app-root > app-getaways-container > app-home-page > div.container.ng-star-inserted > div.clusters-list-container.eva-3-container.ng-star-inserted > div > div:nth-child(3) > app-package-cluster > div')
        self.getaways_mod = (By.CSS_SELECTOR, 'body > app-root > app-getaway-detail-page > app-detail-page > div > div.detail-container > div.re-search > app-detail-re-search > div > div.re-search-container > div > ul > li.re-search-item.re-search-action > app-tooltip-modal > app-tooltip > span > span:nth-child(1) > a')
        self.getaways_sub = (By. CSS_SELECTOR, 'body > app-root > app-getaway-detail-page > app-detail-page > div > div.detail-container > div.re-search > app-modify-date-pax > div > div.modal-content > span > div > div.col.-md-5.-eva-3-pb-xlg.-eva-3-mb-xlg.pax > app-passengers-filter > div > div.rooms-container > div > div:nth-child(2) > div.eva-3-steppers.-md > a.steppers-icon-left.eva-3-icon-minus')
        self.getaways_disp = (By.CSS_SELECTOR, 'body > app-root > app-getaway-detail-page > app-detail-page > div > div.detail-container > div.re-search > app-modify-date-pax > div > div.modal-content > span > div > div.col.-sm-12.-md-12.buttons-container > div.button-container.-eva-3-valign')
        self.getaways_next = (By.CSS_SELECTOR, 'body > app-root > app-getaway-detail-page > app-detail-page > app-detail-pricebox-sticky > pricebox-sticky > div > div.pricebox-content-container > div.buttons-container > button')
    
        #Cars Arguments---#
        self.cars_button = (By. CSS_SELECTOR, 'body > nav > div.header-navigation.-first > div > div.header-products-container > ul > li:nth-child(8)')
        self.cars_destiny = (By. CSS_SELECTOR, '#searchbox-sbox-box-cars > div > div > div > div > div.wrapper--atwWg > div.ovr-places-wrapper--i40EO > div.sbox-places-container--3kBK7.sbox-places-origin-destination > div > div > div > input')
        self.cars_enterdny = (By. CSS_SELECTOR, 'body > div.ac-wrapper.-desktop.-show > div > div:nth-child(1) > ul > li.item.-active')
        self.cars_retire = (By. CSS_SELECTOR, '#searchbox-sbox-box-cars > div > div > div > div > div.wrapper--atwWg > div.ovr-dates-wrapper--3XdtO > div > div.sbox5-dates-input1-container > div > div.sbox5-dates-input1 > div > div > input')
        self.cars_dateret = (By. CSS_SELECTOR, '#component-modals > div > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > div:nth-child(3) > div.sbox5-monthgrid-dates.sbox5-monthgrid-dates-31 > div:nth-child(24)')
        self.cars_datedev = (By. CSS_SELECTOR, '#component-modals > div > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > div:nth-child(4) > div.sbox5-monthgrid-dates.sbox5-monthgrid-dates-30 > div:nth-child(20)')        
        self.cars_search = (By. CSS_SELECTOR, '#searchbox-sbox-box-cars > div > div > div > div > div.wrapper--atwWg > div.ovr-button-wrapper--2HUXm > button')
        self.cars_detail = (By. CSS_SELECTOR, '#results-page > div > div > div.results-container > div > div > div > div.results-page-right.col.-sm-12.-md-12.-lg-9 > div.eva-3-row > div > div > div:nth-child(2) > div > cluster-by-car > div:nth-child(1) > div > div > div.cluster-pricebox-container.flex.flex-direction-column-sm.justify-content-center-md.justify-content-center-lg > pricebox-by-car > div > div.pricebox-info > div:nth-child(4) > next-step-button > div')
    
        #Disney Arguments---#
        self.dsny_button = (By. CSS_SELECTOR, 'body > nav > div.header-navigation.-first > div > div.header-products-container > ul > li:nth-child(9) > a')
        self.dsny_datesel = (By. CSS_SELECTOR, 'body > app-root > detail > div > div > div.detail-cluster-container > ticket-pricebox > div > div.pricebox-top-container > div.pricebox-action > span')
        self.dsny_seldate = (By. CSS_SELECTOR, '#date-picker > div.coachmark-date-picker-container > activities-datepicker > div > div.col.-sm-12 > datepicker-child > div > div > div > input')
        self.dnsy_arrowright = (By. XPATH, '/html/body/div[9]/div/div/div/a[2]')
        self.dsny_date = (By. XPATH, '/html/body/div[9]/div/div/div/div/div[3]/div[31]')
        self.dsny_addcart = (By. XPATH, '/html/body/app-root/detail/div/div/div[3]/detail-pricebox-sticky/pricebox-sticky/div/div[1]/div[2]/button[1]')
        self.dsny_cart = (By. XPATH, '/html/body/app-root/app-results/div/div[1]/div/app-cart/div/div')

        #Assists Arguments---#
        self.assist_button = (By.CSS_SELECTOR, 'body > nav > div.header-navigation.-first > div > div.header-products-container > ul > li:nth-child(10) > a > div > div')
        self.assist_destiny = (By.CSS_SELECTOR, '#searchbox-sbox-box-assistance > div > div > div > div > div.wrapper--qCCl7 > div.ovr-select-wrapper--sZaJo > div > div > div > select')
        self.assist_entdate = (By.CSS_SELECTOR, '#searchbox-sbox-box-assistance > div > div > div > div > div.wrapper--qCCl7 > div.ovr-dates-wrapper--3glhc > div > div.sbox5-dates-input1-container > div > div > div > div > input')
        self.assist_arright = (By.CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > a.calendar-arrow-right')
        self.assist_seldate = (By.CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > div:nth-child(3) > div.sbox5-monthgrid-dates.sbox5-monthgrid-dates-31 > div.sbox5-monthgrid-datenumber.sbox5-monthgrid-datenumber-31')
        self.assist_entexda = (By.CSS_SELECTOR, '#searchbox-sbox-box-assistance > div > div > div > div > div.wrapper--qCCl7 > div.ovr-dates-wrapper--3glhc > div > div.sbox5-dates-input2-container > div > div > div > div > input')
        self.assist_exdate = (By.CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > div:nth-child(4) > div.sbox5-monthgrid-dates.sbox5-monthgrid-dates-30 > div.sbox5-monthgrid-datenumber.sbox5-monthgrid-datenumber-30.-weekday')
        self.assist_apply = (By.CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.calendar-footer > div.calendar-footer-cta-container > button')
        self.assist_search = (By.CSS_SELECTOR, '#searchbox-sbox-box-assistance > div > div > div > div > div.wrapper--qCCl7 > div.ovr-button-wrapper--nrUrv > button')
        self.assist_buy = (By.CSS_SELECTOR, '#slider_id_1 > swiper > div > div.swiper-slide.swiper-slide-next > new-assistance > div > div.cluster-container > pricebox > div > div > div.pricebox-top-container.-align-items-center > div.pricebox-action > button')
    
        #Transfers Arguments---#
        self.transfers_button = (By.CSS_SELECTOR, 'body > nav > div.header-navigation.-first > div > div.header-products-container > ul > li:nth-child(11) > a > div')
        self.transfers_airport = (By.CSS_SELECTOR, '#searchbox-sbox-box-transferspoi > div > div > div > div > div.wrapper--wqjzV > div.sbox5-row-components--2lIfj > div.sbox5-transfers-places-ovr--FrD4r.-fromAirport--7M4Ta > div > div.sbox-places-origin--G_Rvw.sbox-places-origin-destination--1I6U9.sbox-places-orig-override > div > div > input')
        self.transfers_ezeiza = (By.CSS_SELECTOR, 'body > div.ac-wrapper.-desktop.-show > div > div > ul > li > span')
        self.transfers_arrive = (By.CSS_SELECTOR, '#searchbox-sbox-box-transferspoi > div > div > div > div > div.wrapper--wqjzV > div.sbox5-row-components--2lIfj > div.sbox5-transfers-places-ovr--FrD4r.-fromAirport--7M4Ta > div > div.sbox-places-destination--1xd0k.sbox-places-origin-destination--1I6U9.sbox-places-dest-override > div > div > input')
        self.transfers_newyork = (By.CSS_SELECTOR, 'body > div.ac-wrapper.-desktop.-facet.-show.sbox-ab-ls > div > div > ul > li')
        self.transfers_date = (By.CSS_SELECTOR, '#searchbox-sbox-box-transferspoi > div > div > div > div > div.wrapper--wqjzV > div.sbox5-row-components--2lIfj > div.sbox5-transfers-dates-ovr--3B87J > div > div > div > div.sbox5-dates-input1 > div > div > input')
        self.transfers_arright = (By.XPATH, '//*[@id="component-modals"]/div[3]/div[1]/div[2]/a[2]')
        self.transfers_entdate = (By.CSS_SELECTOR, '#component-modals > div.sbox5-floating-tooltip.sbox5-floating-tooltip-opened > div.sbox5-3-floating-tooltip-datepicker-wrapper > div.calendar-container > div:nth-child(3) > div.sbox5-monthgrid-dates.sbox5-monthgrid-dates-31 > div.sbox5-monthgrid-datenumber.sbox5-monthgrid-datenumber-31')
        self.transfers_search = (By.CSS_SELECTOR, '#searchbox-sbox-box-transferspoi > div > div > div > div > div.wrapper--wqjzV > div.sbox5-row-components--2lIfj > div.sbox5-button-container--BgC6V > button')
        self.transfers_buy = (By.CSS_SELECTOR, 'body > app-root > results > div > div.eva-3-row.clusters-container.-eva-3-mt-xxlg > div:nth-child(1) > transfer-cluster > div > div > div.cluster-pricebox-container > ds-cluster-pricebox > div > div.pricebox-top-container > div.pricebox-action > button')
    #-------------------------------------------#

    def switch_to_tab(self, tab_index):
        windows = self.driver.window_handles
        self.driver.switch_to.window(windows[tab_index])
    
    def home(self):
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.flights_button)).click()
        time.sleep(5)

    def accommodations(self):
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.unnders)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.close)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.accomm)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.dates)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.arrow_right)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.accomodation_enterdate)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.exitdate)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.accomodation_exdate)).click()        
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.apply)).click()
        time.sleep(2)
        self.driver.find_element(*self.city).click()
        time.sleep(2)
        self.driver.find_element(*self.city).send_keys('Cordo')
        time.sleep(2)
        self.driver.find_element(*self.destiny).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.search_button)).click()
        clase = Select(self.driver.find_element(*self.order_by))
        clase.select_by_visible_text('Precio: menor a mayor')
        time.sleep(1)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.view_detail)).click()
        time.sleep(2)
        self.switch_to_tab(1)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.view_rooms)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.room_reserve)).click()        

    def flights(self):
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.unnders)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.close)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.flights_button)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.flight_date)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.enter_flight_date)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.exitflight_date)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.enter_exitflight_date)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.passengers_class)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.adult_plus)).click()
        time.sleep(1)
        for i in range(3):
            self.driver.find_element(*self.menor_plus).click()        
        time.sleep(1)
        menor1 = Select(self.driver.find_element(*self.age_menor1))
        menor1.select_by_visible_text('10 años')
        time.sleep(1)
        menor2 = Select(self.driver.find_element(*self.age_menor2))
        menor2.select_by_visible_text('12 años')
        time.sleep(1)
        menor3 = Select(self.driver.find_element(*self.age_menor3))
        menor3.select_by_visible_text('15 años')
        time.sleep(1)
        clase = Select(self.driver.find_element(*self.clase))
        clase.select_by_visible_text('Primera Clase')        
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.flight_apply)).click()        
        self.driver.find_element(*self.flight_destiny).click()
        time.sleep(1)
        self.driver.find_element(*self.flight_destiny).send_keys('cordoba')
        time.sleep(2)
        self.driver.find_element(*self.destiny).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.flight_search)).click()        
        time.sleep(5)
    
    def packages(self):        
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.unnders)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.close)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.packages_button)).click()
        time.sleep(1)
        self.driver.find_element(*self.package_destiny).click()
        time.sleep(1)
        self.driver.find_element(*self.package_destiny).send_keys('nueva')
        time.sleep(1)
        self.driver.find_element(*self.destiny).click()
        time.sleep(1)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.package_rooms)).click()
        time.sleep(2)
        button = self.driver.find_element(*self.package_substract)
        button.click()
        time.sleep(2)
        apply = self.driver.find_element(*self.packagerooms_apply)
        apply.click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.package_notdate)).click()        
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.package_search)).click()
        try:
            WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.package_travel)).click()
        except:
            WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.package_travel_aux)).click()
        time.sleep(10)
    
    def offers(self):
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.unnders)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.close)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.offers_button)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.offer_package)).click()
        time.sleep(2)
        self.switch_to_tab(1)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.view_travel)).click()
        time.sleep(5)
        self.switch_to_tab(2)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.travel_next)).click()
        time.sleep(5)
        self.switch_to_tab(3)
        time.sleep(5)        
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.continue_travel)).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.buy_button)).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.continue_2)).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.endoffer)).click()
    
    def rents(self):
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.unnders)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.close)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.rents_button)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.rents_destiny)).click()
        time.sleep(2)     
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.rents_destiny)).send_keys('cord')
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.rents_cordoba)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.rents_enterdate)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.rents_date)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.rents_exitdate)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.rents_date2)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.rents_applydate)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.rents_search)).click()

    def activities(self):
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.unnders)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.close)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.activ_button)).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.activ_enterdestiny)).click()
        time.sleep(2)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.activ_enterdestiny)).send_keys('Buen')
        time.sleep(2)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.activ_destiny)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.activ_search)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.activ_select)).click()
        time.sleep(2)
        self.switch_to_tab(1)        
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.activ_seeoption)).click()
        time.sleep(2)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.activ_sel_date)).click()
        time.sleep(2)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.activ_arrowright)).click()
        time.sleep(2)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.activ_ddate)).click()       
        tim = Select(self.driver.find_element(*self.activ_sel_time))
        tim.select_by_visible_text("20:00")
        time.sleep(5)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.activ_add)).click()
        time.sleep(2)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable(self.activ_cart)).click()
        time.sleep(10)

    def getaways(self):
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.unnders)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.close)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.getaways_button)).click()
        try:
            WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.getaways_culture)).click()
        except:
            time.sleep(2)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.getaways_destiny)).click()
        time.sleep(2)
        self.switch_to_tab(1)
        time.sleep(2)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.getaways_mod)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.getaways_sub)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.getaways_disp)).click()
        time.sleep(5)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.getaways_next)).click()

    def cars(self):
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.unnders)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.close)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.cars_button)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.cars_destiny)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.cars_destiny)).send_keys('Buenos')
        time.sleep(2)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.cars_enterdny)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.cars_retire)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.arrow_right)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.cars_dateret)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.cars_datedev)).click()
        time.sleep(2)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.apply)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.cars_search)).click()
        time.sleep(2)
        try:
            WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.cars_detail)).click()
            time.sleep(2)
            self.switch_to_tab(1)
        except:
            time.sleep(1)
    
    def dsny(self):
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.unnders)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.close)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.dsny_button)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.dsny_datesel)).click()        
        time.sleep(2)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.dnsy_arrowright)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.dsny_date)).click()
        time.sleep(15)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.dsny_addcart)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.dsny_cart)).click()
        time.sleep(2)
    
    def assists(self):
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.unnders)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.close)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.assist_button)).click()
        time.sleep(2)
        destiny = Select(WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.assist_destiny)))
        destiny.select_by_visible_text('Argentina')
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.assist_entdate)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.assist_arright)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.assist_seldate)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.assist_entexda)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.assist_exdate)).click()
        time.sleep(1)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.assist_apply)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.assist_search)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.assist_buy)).click()
        time.sleep(2)
    
    def transfers(self):
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.unnders)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.close)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_button)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_airport)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_airport)).send_keys('ezei')
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_ezeiza)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_arrive)).click()
        time.sleep(2)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_arrive)).send_keys('icar')
        time.sleep(2)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_newyork)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_date)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_arright)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_entdate)).click()
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_search)).click()
        time.sleep(3)
        WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(self.transfers_buy)).click()